// This file is generated by Firebase Studio.
'use server';
/**
 * @fileOverview This file defines a Genkit flow to analyze self-evaluation and manager feedback to identify key strengths and areas for improvement for an employee.
 *
 * - generatePerformanceInsights - A function that triggers the performance insights generation flow.
 * - GeneratePerformanceInsightsInput - The input type for the generatePerformanceInsights function.
 * - GeneratePerformanceInsightsOutput - The return type for the generatePerformanceInsights function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const GeneratePerformanceInsightsInputSchema = z.object({
  employeeId: z.string().describe('The ID of the employee.'),
  selfEvaluation: z.record(z.string(), z.string()).describe('The self-evaluation data for the employee. Each key represents the criteria and the value represents the feedback.'),
  managerFeedback: z.record(z.string(), z.string()).describe('The manager feedback data for the employee. Each key represents the criteria and the value represents the feedback.'),
});

export type GeneratePerformanceInsightsInput = z.infer<typeof GeneratePerformanceInsightsInputSchema>;

const GeneratePerformanceInsightsOutputSchema = z.object({
  strengths: z.string().describe('Key strengths of the employee based on the evaluation and feedback.'),
  areasForImprovement: z.string().describe('Areas for improvement for the employee based on the evaluation and feedback.'),
});

export type GeneratePerformanceInsightsOutput = z.infer<typeof GeneratePerformanceInsightsOutputSchema>;

export async function generatePerformanceInsights(input: GeneratePerformanceInsightsInput): Promise<GeneratePerformanceInsightsOutput> {
  return generatePerformanceInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePerformanceInsightsPrompt',
  input: {
    schema: z.object({
      employeeId: z.string().describe('The ID of the employee.'),
      selfEvaluation: z.record(z.string(), z.string()).describe('The self-evaluation data for the employee.'),
      managerFeedback: z.record(z.string(), z.string()).describe('The manager feedback data for the employee.'),
    }),
  },
  output: {
    schema: z.object({
      strengths: z.string().describe('Key strengths of the employee.'),
      areasForImprovement: z.string().describe('Areas for improvement for the employee.'),
    }),
  },
  prompt: `You are a performance analysis expert. Analyze the self-evaluation and manager feedback provided below to identify key strengths and areas for improvement for the employee.

  Here's an example of good feedback:
  "SME: [Self] I have a strong understanding of the core concepts in my domain. [Manager] John is a recognized expert in the team and is often consulted for his knowledge."

  When analyzing the feedback, consider the following:
  - Look for patterns and themes in the feedback.
  - Identify specific skills or behaviors mentioned.
  - Note any discrepancies or agreements between self-evaluation and manager feedback.

  Employee ID: {{{employeeId}}}

  Self-Evaluation:
  {{#each selfEvaluation}}
  {{@key}}: {{#if @value}}{{@value}}{{else}}No feedback provided{{/if}}
  {{/each}}

  Manager Feedback: 
  {{#each managerFeedback}}
  {{@key}}: {{@value}}
  {{/each}}

  Based on the above information, provide a concise summary of the employee's key strengths and areas for improvement.

  Strengths:
  
  Areas for Improvement:
  `,
});

const generatePerformanceInsightsFlow = ai.defineFlow<
  typeof GeneratePerformanceInsightsInputSchema,
  typeof GeneratePerformanceInsightsOutputSchema
>(
  {
    name: 'generatePerformanceInsightsFlow',
    inputSchema: GeneratePerformanceInsightsInputSchema,
    outputSchema: GeneratePerformanceInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
